dubbo:
  application:
    name: dubbo-test-consumer
    owner: GavinYau
  registry:
    address: zookeeper://127.0.0.1:2181 # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  consumer:
    timeout: 3000
  version: 1.0.0

