dubbo:
  application:
    name: dubbo-test-service
    owner: GavinYau
  registry:
    address: nacos://139.196.101.123:8848/
  metadata-report:
    address: nacos://139.196.101.123:2181
  protocol:
    name: dubbo
    port: -1
  version: 1.0.0
